# Generated by Django 5.2 on 2025-05-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='carrera',
        ),
    ]
