# Generated by Django 5.2 on 2025-05-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_remove_estudiante_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='codigo',
            field=models.CharField(default='sin-codigo', max_length=10),
            preserve_default=False,
        ),
    ]
