# Generated by Django 5.2 on 2025-05-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_materia_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='fecha_matricula',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='nota_final',
        ),
        migrations.AddField(
            model_name='matricula',
            name='ciclo',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
