# Generated by Django 5.2 on 2025-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_remove_matricula_fecha_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='cargos'),
        ),
    ]
