# Generated by Django 5.2 on 2025-05-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_materia_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='cargos'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='cargos'),
        ),
    ]
