# Generated by Django 5.2 on 2025-05-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_estudiante_logo_matricula_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
